# Generated by Django 5.2.2 on 2025-06-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productimage_options_productimage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('TOTEBAG', 'Totebag'), ('TSHIRT', 'T-Shirt')], default='TOTEBAG', max_length=10),
        ),
    ]
