# Generated by Django 5.2.2 on 2025-06-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.CharField(blank=True, choices=[('WHITE', 'White'), ('BLACK', 'Black'), ('RED', 'Red'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('YELLOW', 'Yellow')], max_length=10, null=True),
        ),
    ]
