# Generated by Django 5.2.2 on 2025-06-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_available_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(blank=True, help_text='Comma-separated sizes (e.g., S,M,L,XL) for T-shirts', max_length=100, null=True),
        ),
    ]
